### ISSUE TITLE
Generated terraform failing terraform validate

### ISSUE THREAD

**Issue by bviswanathan-exelixis** [DontShaveTheYak/cf2tf#211]
Trying to convert CF template to TF from repo - https://github.com/tlh2857/xdr-aws-integration/tree/main. The resulting terraform is failing `terraform validate` Terraform plan also returns several errors -> 

var.cloud_trail_bucket_name
  The name of the S3 Bucket to create for storing CloudTrail Logs.

  Enter a value: cloudtrail_s3

var.external_id
  A Random UUID that you generate as an added layer of security. Can use online UUID generator. Will share with IAM Assume Role and with Cortex XDR.

  Enter a value: <value>

var.flow_logs_bucket_name
  The name of the S3 Bucket to create for storing VPC Flow Logs.

  Enter a value: vpc_flow_logs_s3

var.role_name
  The name that you want to give to the role that Cortex XDR will assume in order to pull logs from the SQS queue

  Enter a value: aws_cortex_sdr_role

var.route53_bucket_name
  The name of the S3 Bucket to create for storing Route53 Logs.

  Enter a value: r53_s3

╷
│ Error: Incorrect attribute value type
│ 
│   on xdr-aws.tf line 45, in resource "aws_iam_role" "xdr_role":
│   45:   assume_role_policy = {
│   46:     Version = "2012-10-17"
│   47:     Statement = [
│   48:       {
│   49:         Effect = "Allow"
│   50:         Action = [
│   51:           "sts:AssumeRole"
│   52:         ]
│   53:         Principal = {
│   54:           AWS = "<value>"
│   55:         }
│   56:         Condition = {
│   57:           StringEquals = {
│   58:             "sts:ExternalId" : var.external_id,
│   59:           }
│   60:         }
│   61:       }
│   62:     ]
│   63:   }
│     ├────────────────
│     │ var.external_id is a string
│ 
│ Inappropriate value for attribute "assume_role_policy": string required.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on xdr-aws.tf line 69, in resource "aws_iam_role" "xdr_role":
│   69:   force_detach_policies = [
│   70:     {
│   71:       PolicyName = "xdr-inline-policy"
│   72:       PolicyDocument = {
│   73:         Version = "2012-10-17"
│   74:         Statement = [
│   75:           {
│   76:             Effect = "Allow"
│   77:             Action = "s3:GetObject"
│   78:             Resource = [
│   79:               "arn:aws:s3:::${var.cloud_trail_bucket_name}/*",
│   80:               "arn:aws:s3:::${var.route53_bucket_name}/*",
│   81:               "arn:aws:s3:::${var.flow_logs_bucket_name}/*"
│   82:             ]
│   83:           },
│   84:           {
│   85:             Effect = "Allow"
│   86:             Action = [
│   87:               "sqs:ReceiveMessage",
│   88:               "sqs:DeleteMessage",
│   89:               "sqs:ChangeMessageVisibility"
│   90:             ]
│   91:             Resource = [
│   92:               aws_sqs_queue.route53_sqs_queue.arn,
│   93:               aws_sqs_queue.flow_logs_sqs_queue.arn,
│   94:               aws_sqs_queue.cloud_trail_sqs_queue.arn
│   95:             ]
│   96:           }
│   97:         ]
│   98:       }
│   99:     }
│  100:   ]
│     ├────────────────
│     │ var.cloud_trail_bucket_name is a string
│     │ var.flow_logs_bucket_name is a string
│     │ var.route53_bucket_name is a string
│ 
│ Inappropriate value for attribute "force_detach_policies": bool required.
╵
╷
│ Error: Unsupported argument
│ 
│   on xdr-aws.tf line 106, in resource "aws_s3_bucket" "route53_s3_bucket":
│  106:   replication_configuration = {
│ 
│ An argument named "replication_configuration" is not expected here. Did you
│ mean to define a block of type "replication_configuration"?
╵
╷
│ Error: Unsupported argument
│ 
│   on xdr-aws.tf line 118, in resource "aws_s3_bucket" "flow_logs_s3_bucket":
│  118:   replication_configuration = {
│ 
│ An argument named "replication_configuration" is not expected here. Did you
│ mean to define a block of type "replication_configuration"?
╵
╷
│ Error: Unsupported argument
│ 
│   on xdr-aws.tf line 130, in resource "aws_s3_bucket" "cloud_trail_s3_bucket":
│  130:   replication_configuration = {
│ 
│ An argument named "replication_configuration" is not expected here. Did you
│ mean to define a block of type "replication_configuration"?
╵
╷
│ Error: Missing required argument
│ 
│   on xdr-aws.tf line 221, in resource "aws_sqs_queue_policy" "route53_queue_policy":
│  221: resource "aws_sqs_queue_policy" "route53_queue_policy" {
│ 
│ The argument "queue_url" is required, but no definition was found.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on xdr-aws.tf line 222, in resource "aws_sqs_queue_policy" "route53_queue_policy":
│  222:   policy = {
│  223:     Version = "2012-10-17"
│  224:     Statement = [
│  225:       {
│  226:         Effect = "Allow"
│  227:         Principal = {
│  228:           AWS = "*"
│  229:         }
│  230:         Action = [
│  231:           "SQS:SendMessage"
│  232:         ]
│  233:         Resource = aws_sqs_queue.route53_sqs_queue.arn
│  234:       }
│  235:     ]
│  236:   }
│ 
│ Inappropriate value for attribute "policy": string required.
╵
╷
│ Error: Missing required argument
│ 
│   on xdr-aws.tf line 242, in resource "aws_sqs_queue_policy" "flow_logs_queue_policy":
│  242: resource "aws_sqs_queue_policy" "flow_logs_queue_policy" {
│ 
│ The argument "queue_url" is required, but no definition was found.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on xdr-aws.tf line 243, in resource "aws_sqs_queue_policy" "flow_logs_queue_policy":
│  243:   policy = {
│  244:     Version = "2012-10-17"
│  245:     Statement = [
│  246:       {
│  247:         Effect = "Allow"
│  248:         Principal = {
│  249:           AWS = "*"
│  250:         }
│  251:         Action = [
│  252:           "SQS:SendMessage"
│  253:         ]
│  254:         Resource = aws_sqs_queue.flow_logs_sqs_queue.arn
│  255:       }
│  256:     ]
│  257:   }
│ 
│ Inappropriate value for attribute "policy": string required.
╵
╷
│ Error: Missing required argument
│ 
│   on xdr-aws.tf line 263, in resource "aws_sqs_queue_policy" "cloud_trail_queue_policy":
│  263: resource "aws_sqs_queue_policy" "cloud_trail_queue_policy" {
│ 
│ The argument "queue_url" is required, but no definition was found.
╵
╷
│ Error: Incorrect attribute value type
│ 
│   on xdr-aws.tf line 264, in resource "aws_sqs_queue_policy" "cloud_trail_queue_policy":
│  264:   policy = {
│  265:     Version = "2012-10-17"
│  266:     Statement = [
│  267:       {
│  268:         Effect = "Allow"
│  269:         Principal = {
│  270:           AWS = "*"
│  271:         }
│  272:         Action = [
│  273:           "SQS:SendMessage"
│  274:         ]
│  275:         Resource = aws_sqs_queue.cloud_trail_sqs_queue.arn
│  276:       }
│  277:     ]
│  278:   }
│ 
│ Inappropriate value for attribute "policy": string required.
╵

**Comment by kzehnter** [comment]
Hey, I'm pretty sure right now you cant expect the generated code to work immediately. It doesn't work that well yet. Try fixing the individual problems and look at what happened for each situation. It is probably more helpful for the developers here if you split up individual problems into individual issues.
To solve these problems, check if the resources in the TF code match the CF resources. Sometimes it chooses wrong ones.
Then look at the Terraform Documentation for each failing resource and find the missing stuff. For most problems you will quickly find the reason for the error.

If you have any specific questions feel free to ask

**Comment by bviswanathan-exelixis** [comment]
@kzehnter Thanks. I think it would be good if the tool can take in a cf (json) file directly and skip the intermediate yaml. AWS designer converts json to yaml but it looks converting some existing template results in errors.

**Comment by shadycuz** [comment]
@bviswanathan-exelixis Unfortunately @kzehnter  is correct, we are not able to make a 100% conversion and likely never will. That has to do with Cloudformation not having explicit types and Terraform does. So we have to guess what to do most of the time when converting from CF to TF. There is a link at the top of the README that goes into a bit more detail on the challenges of converting. 

For simple templates this works pretty well and with complicated ones, not so much. But we are hoping to one day get the conversion to about 95% complete. I think we are at about 80-90% today, depending on how complicated the template is.

If you see problems with the conversion, feel free to report them in individual issues and we will try to fix them. 

>  I think it would be good if the tool can take in a cf (json) file directly and skip the intermediate yaml

I convert json templates all the time with no problem.


I will close this for now, because failing to validate is somewhat expected without human intervention.
