### ISSUE TITLE
data "aws_availability_zones" needs to be created when referenced

### ISSUE THREAD

**Issue by kzehnter** [DontShaveTheYak/cf2tf#215]
**Expected Behaviour:**
When the conversion utilizes `data.aws_availability_zones.available.names` the following data block gets created as well.
```
data "aws_availability_zones" "available" {
  state = "available"
}
```

**Actual Behaviour:**
The data block does not get created so the code doesn't work.

Found with this conversion:
```
      AvailabilityZone: !Select 
        - 0
        - !GetAZs ''
```
to
```
  availability_zone = element(data.aws_availability_zones.available.names, 0)
```

**Comment by shadycuz** [comment]
Thanks for reporting this.

**Comment by shadycuz** [comment]
I can't seem to replicate this as I do see the data block being added. But I do see a bug in the name of the data block 

```HCL
data "availability_zones" "available" {
  state = "available"
}
```

Should be `aws_availability_zones`.
