### ISSUE TITLE
Maps are not displayed correctly and anytrue function inputs are misquoted

### ISSUE THREAD

**Issue by cognitiaclaeves** [DontShaveTheYak/cf2tf#23]
Here is the CFN that I'm converting:

https://gitlab.com/cogz-public-cloud/aws/cf2tf-api-lambda/-/blob/main/api-lambda.cfn.json

( There is also a YAML version )

The TF generated appears to be unusable.

In both cases, I see errors like this when I try to run TF validate:

╷
│ Error: Invalid character
│ 
│   on locals.tf line 2, in locals:
│    2:   CDKMetadataAvailable = anytrue(['anytrue([\'data.aws_region.current.name == "af-south-1"\', \'data.aws_region.current.name == "ap-east-1"\', \'data.aws_region.current.name == "ap-northeast-1"\', \'data.aws_region.current.name == "ap-northeast-2"\', \'data.aws_region.current.name == "ap-south-1"\', \'data.aws_region.current.name == "ap-southeast-1"\', \'data.aws_region.current.name == "ap-southeast-2"\', \'data.aws_region.current.name == "ca-central-1"\', \'data.aws_region.current.name == "cn-north-1"\', \'data.aws_region.current.name == "cn-northwest-1"\'])', 'anytrue([\'data.aws_region.current.name == "eu-central-1"\', \'data.aws_region.current.name == "eu-north-1"\', \'data.aws_region.current.name == "eu-south-1"\', \'data.aws_region.current.name == "eu-west-1"\', \'data.aws_region.current.name == "eu-west-2"\', \'data.aws_region.current.name == "eu-west-3"\', \'data.aws_region.current.name == "me-south-1"\', \'data.aws_region.current.name == "sa-east-1"\', \'data.aws_region.current.name == "us-east-1"\', \'data.aws_region.current.name == "us-east-2"\'])', 'anytrue([\'data.aws_region.current.name == "us-west-1"\', \'data.aws_region.current.name == "us-west-2"\'])'])
│ 
│ This character is not used within the language.
╵

╷
│ Error: Invalid character
│ 
│   on resource.tf line 3, in resource "aws_iam_role" "hello_handler_service_role11_ef7_c63":
│    3:     Statement = [{'Action': '"sts:AssumeRole"', 'Effect': '"Allow"', 'Principal': {'Service': '"lambda.amazonaws.com"'}}]
│ 
│ Single quotes are not valid. Use double quotes (") to enclose strings.
╵

This project uses CFN generated by CDK synth.

By the way, I originally tried to run cf2tf in the CloudShell, and found that installation broke when trying to install python-Levenshtein. The project appeared to be at least a little out-of-date.

**Comment by shadycuz** [comment]
From the README.md

> cf2tf is a CLI tool that **attempts** to convert Cloudformation to Terraform. We say attempt because it's not really possible to make the conversion with 100% accuracy (currently) because of several reasons mostly around converting a Map value in Cloudformation to the https://github.com/hashicorp/hcl/issues/294#issuecomment-446388342.

This is a very early application `v0.2.1`. Currently `cf2tf` is able to do about 75% of the conversion for you. On some simple templates, it might pass `terraform validate` but even then I expect deployment to fail. 

The locals block is a bug that was already reported. The other issue is something much more difficult to tackle, but hopefully, I will make some progress soon. 

Stay on the lookout for future improvements.

**Comment by shadycuz** [comment]
In the upcoming release of cf2tf the locals block would now look like:
```hcl
locals {
  CDKMetadataAvailable = anytrue([anytrue([data.aws_region.current.name == "af-south-1", data.aws_region.current.name == "ap-east-1", data.aws_region.current.name == "ap-northeast-1", data.aws_region.current.name == "ap-northeast-2", data.aws_region.current.name == "ap-south-1", data.aws_region.current.name == "ap-southeast-1", data.aws_region.current.name == "ap-southeast-2", data.aws_region.current.name == "ca-central-1", data.aws_region.current.name == "cn-north-1", data.aws_region.current.name == "cn-northwest-1"]), anytrue([data.aws_region.current.name == "eu-central-1", data.aws_region.current.name == "eu-north-1", data.aws_region.current.name == "eu-south-1", data.aws_region.current.name == "eu-west-1", data.aws_region.current.name == "eu-west-2", data.aws_region.current.name == "eu-west-3", data.aws_region.current.name == "me-south-1", data.aws_region.current.name == "sa-east-1", data.aws_region.current.name == "us-east-1", data.aws_region.current.name == "us-east-2"]), anytrue([data.aws_region.current.name == "us-west-1", data.aws_region.current.name == "us-west-2"])])
}
```

Not the prettiest thing but I think its valid Terraform.  The IAM role would be:

```hcl
resource "aws_iam_role" "hello_handler_service_role11_ef7_c63" {
  assume_role_policy = {
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
    Version = "2012-10-17"
  }
  managed_policy_arns = [
    join("", ["arn:", data.aws_partition.current.partition, ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"])
  ]
}
```

This is now valid HCL syntax but the `assume_role_policy` argument takes a JSON string, so you need to wrap the value in `jsonencode()`. 

I have also added an overrides feature to cf2tf. So if you add an override [here](https://github.com/DontShaveTheYak/cf2tf/blob/develop/src/cf2tf/conversion/overrides.py), similar to how I did for `s3_bucket_policy`, than everyone would benefit.
