### ISSUE TITLE
created locals are referenced by "locals." but should be "local."

### ISSUE THREAD

**Issue by zhujik** [DontShaveTheYak/cf2tf#263]
tf output generates references to locals (e.g. converted from conditions) by ```locals.``` which is wrong, it should be ```local.```

**Comment by joaquin386** [comment]
To be fix here: https://github.com/DontShaveTheYak/cf2tf/blob/5a0071435a12bb647193f14c5d9253d5f222b785/src/cf2tf/convert.py#L367C63-L367C64

**Comment by shadycuz** [comment]
@joaquin386 A PR would be welcome, but I will get to it in a week or two if not.

**Comment by joaquin386** [comment]
https://github.com/DontShaveTheYak/cf2tf/pull/274
