### ISSUE TITLE
 find() removes numbers from resource types

### ISSUE THREAD

**Issue by EliaBoschiero** [DontShaveTheYak/cf2tf#47]
line 27 in code.py (name = cf2tf.convert.camel_case_split(name).lower().strip() )
if the resource type contains a number (Ex. AWS::ApiGatewayV2::Integration) the `name` variable has no V2 in it, causing the search to find the incorrect documentation (api_gateway_integration instead of apigatewayv2_integration) and may lead to failing the conversion, in this example because api_gateway_integration has no Attributes Reference, this can easily be fixed by changing the regex in the camel_case_split method

**Comment by shadycuz** [comment]
Another nice find. I will try and look into it tonight or Saturday morning.

**Comment by shadycuz** [comment]
@EliaBoschiero It's been released! Let me know if it doesn't work.
