### ISSUE TITLE
Missing binary?

### ISSUE THREAD

**Issue by mikemcdermottredjack** [DontShaveTheYak/cf2tf#55]
This tool looks amazing, but I can't use it. I executed: 

`pip3 install cf2tf` 

and it was installed under my site-packages folder, but there is no binary. Is this a bug, or is there some other step that maybe should appear in the documentation to get the binary? 

Edit: I am using MacOS and Python 3.8

**Comment by shadycuz** [comment]
An executable should have been installed to your system but its likely that the location is not in your PATH. I do not have MAC so I can not test but a quick google search found this https://www.kisphp.com/os-x/find-pip-package-executable-on-mac

**Comment by shadycuz** [comment]
On my machine I use `python3 -m site --user-base` to show where executables will be installed. The direcory should contain a `bin` which is the localtion of the executable

```console
$ python3 -m site --user-base
/home/shadycuz/.local
$ ls ~/.local/
bin  lib  share

**Comment by mikemcdermottredjack** [comment]
That worked for me, thanks!
