### ISSUE TITLE
Readme lists Cloud-Radar as a dependency

### ISSUE THREAD

**Issue by elvis2** [DontShaveTheYak/cf2tf#63]
Hello,

I wanted to ask if the readme can be updated, to include the cloud-radar pip install? It seems cloud-radar was not installed on my machine (using python3.8). I had to install cloud-radar separately.

**Comment by shadycuz** [comment]
Hello =)

Cloud-Radar is not required. I had no idea why you thought it should be, so I did a search in this repo for the word and found it in the readme 🙃. 

That is a copy/paste error from another project of mine. It's not needed to use `cf2tf` but if you want to test Cloudformation templates its a really cool project.  https://github.com/DontShaveTheYak/cloud-radar

I will replace "Cloud-Radar" in the readme with "Cloudformation 2 Terraform". 

Thanks for opening the issue 👍

**Comment by shadycuz** [comment]
Closed vie #76
