### ISSUE TITLE
!Importvalue function conversation to Relevant terraform code

### ISSUE THREAD

**Issue by dezzertfox** [DontShaveTheYak/cf2tf#69]
I am trying to use this source code ato convert cfn template to tf .
   issue am facing is while converting !Import value  fun which is intrinsic to Cfn  and No parallel in Terraform.. 
   is this issue resolved or we are still following up  please suggest way out.

**Comment by dezzertfox** [comment]
@shadycuz  can you please suggets on this

**Comment by shadycuz** [comment]
@xentripetal your input was very valuable last time, can you think of a better way to handle the Cloudformation `!ImportValue` intrinsic function?

**Comment by shadycuz** [comment]
relevant code here... in case someone wants to take a crack at it. I wont be able to look at it until friday? or so. 

https://github.com/DontShaveTheYak/cf2tf/blob/5ab3137563c6287b7e7c334225afa84bd17dfeba/src/cf2tf/conversion/expressions.py#L483-L491

**Comment by shadycuz** [comment]
This was completed in #132
