### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by ofir-wurmbrand** [DontShaveTheYak/cf2tf#72]
This tool seems really great, but I cannot adopt it because of the weird output format.
what I mean by this is that for some reason all keys and values have a single quote (') on top of the double quote that already exists, or that they don't have them in the right places to begin with. 

Like in this example `Statement = [{'Action': '"sts:AssumeRole"',`
Where it should be like this `    "Statement" : [{"Action" : "sts:AssumeRole",`

As well as that all the actions are printed in a single line, making it not human readable.

**Comment by shadycuz** [comment]
That's because maps are currently not supported but are on the road map.

**Comment by ofir-wurmbrand** [comment]
Ah, ok Thanks for the update.

**Comment by shadycuz** [comment]
This is fixed in the next release which will be out Monday. Example:
```hcl
resource "aws_iam_role" "hello_handler_service_role11_ef7_c63" {
  assume_role_policy = {
    Statement = [
      {
        Action = "sts:AssumeRole"
        Effect = "Allow"
        Principal = {
          Service = "lambda.amazonaws.com"
        }
      }
    ]
    Version = "2012-10-17"
  }
  managed_policy_arns = [
    join("", ["arn:", data.aws_partition.current.partition, ":iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"])
  ]
}
```

Note that the above is valid HCL2 syntax but it is still not valid Terraform. In this instance `assume_role_policy` would take a JSON string, so you would need to wrap the value in a `jsonencode()`.
